Added scripts

diff --git a/.config/hypr/scripts/autostart b/.config/hypr/scripts/autostart
--- a/.config/hypr/scripts/autostart
+++ b/.config/hypr/scripts/autostart
@@ -1,5 +1,33 @@
 #!/bin/bash
 
-hyprctl dispatch workspace 8
-thunderbird &
-hyprctl dispatch workspace 1
+usage() {
+    echo "Usage: autostart [start|stop]"
+    exit 1
+}
+
+# Get value of argument (action: start|stop)
+action=$1
+
+
+# Check if the argument is empty
+if [ -z "$action" ]; then
+    usage
+fi
+
+if [ "$action" == "start" ]; then
+	waybar &
+    hyprpaper &
+    hypridle &
+    swaync &
+    hyprctl dispatch exec [workspace 8 silent] thunderbird
+elif [ "$action" == "stop" ]; then
+	killall waybar
+    killall hyprpaper
+    killall hypridle
+    killall swaync
+    killall thunderbird
+else
+    echo "Invalid action: $action"
+    usage
+fi
+
diff --git a/.config/hypr/scripts/clip b/.config/hypr/scripts/clip
--- a/.config/hypr/scripts/clip
+++ b/.config/hypr/scripts/clip
@@ -1,3 +1,23 @@
 #!/bin/bash
 
-cliphist list | rofi -dmenu -p "Clipboard" -i -theme "$HOME/.config/rofi/clip.rasi"| cliphist decode | wl-copy
+usage() {
+    echo "Usage: clip [clip|clear]"
+    exit 1
+}
+
+# Get value of argument (action: clip, clear)
+action=$1
+
+if [ -z "$action" ]; then
+    usage
+fi
+
+if [ "$action" == "clip" ]; then
+    cliphist list | rofi -dmenu -p "Clipboard" -i -theme "$HOME/.config/rofi/clip.rasi"| cliphist decode | wl-copy
+elif [ "$action" == "clear" ]; then
+    cliphist wipe
+    notify-send -i /usr/share/icons/AdwaitaLegacy/48x48/legacy/edit-clear-all.png "Clipboard" "Clipboard history has been cleared."
+else
+    echo "Invalid action: $action"
+    usage
+fi
